// This file is @generated by prost-build.
/// Request/Response messages
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MeanReversionRequest {
    #[prost(double, repeated, tag = "1")]
    pub prices: ::prost::alloc::vec::Vec<f64>,
    #[prost(double, tag = "2")]
    pub threshold: f64,
    #[prost(int32, tag = "3")]
    pub lookback: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MeanReversionResponse {
    #[prost(double, tag = "1")]
    pub signal: f64,
    #[prost(double, tag = "2")]
    pub zscore: f64,
    #[prost(bool, tag = "3")]
    pub entry_signal: bool,
    #[prost(bool, tag = "4")]
    pub exit_signal: bool,
    #[prost(map = "string, double", tag = "5")]
    pub metrics: ::std::collections::HashMap<::prost::alloc::string::String, f64>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PortfolioOptimizationRequest {
    #[prost(message, repeated, tag = "1")]
    pub prices: ::prost::alloc::vec::Vec<PriceVector>,
    /// "markowitz", "risk_parity", "equal_weight", "min_variance"
    #[prost(string, tag = "2")]
    pub method: ::prost::alloc::string::String,
    #[prost(map = "string, double", tag = "3")]
    pub parameters: ::std::collections::HashMap<::prost::alloc::string::String, f64>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriceVector {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(double, repeated, tag = "2")]
    pub prices: ::prost::alloc::vec::Vec<f64>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PortfolioOptimizationResponse {
    #[prost(double, repeated, tag = "1")]
    pub weights: ::prost::alloc::vec::Vec<f64>,
    #[prost(double, tag = "2")]
    pub expected_return: f64,
    #[prost(double, tag = "3")]
    pub volatility: f64,
    #[prost(double, tag = "4")]
    pub sharpe_ratio: f64,
    #[prost(map = "string, double", tag = "5")]
    pub metrics: ::std::collections::HashMap<::prost::alloc::string::String, f64>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegimeDetectionRequest {
    #[prost(double, repeated, tag = "1")]
    pub returns: ::prost::alloc::vec::Vec<f64>,
    #[prost(int32, tag = "2")]
    pub n_regimes: i32,
    #[prost(int32, tag = "3")]
    pub n_iterations: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegimeDetectionResponse {
    #[prost(int32, tag = "1")]
    pub current_regime: i32,
    #[prost(double, repeated, tag = "2")]
    pub regime_probabilities: ::prost::alloc::vec::Vec<f64>,
    #[prost(message, repeated, tag = "3")]
    pub regimes: ::prost::alloc::vec::Vec<RegimeParameters>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegimeParameters {
    #[prost(double, tag = "1")]
    pub mean: f64,
    #[prost(double, tag = "2")]
    pub volatility: f64,
    #[prost(double, tag = "3")]
    pub persistence: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamRequest {
    #[prost(string, repeated, tag = "1")]
    pub symbols: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "2")]
    pub exchange: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub interval_ms: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketDataUpdate {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub timestamp: i64,
    #[prost(double, tag = "3")]
    pub bid: f64,
    #[prost(double, tag = "4")]
    pub ask: f64,
    #[prost(double, tag = "5")]
    pub mid: f64,
    #[prost(double, tag = "6")]
    pub volume: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderBookRequest {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub exchange: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub depth: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderBookResponse {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub timestamp: i64,
    #[prost(message, repeated, tag = "3")]
    pub bids: ::prost::alloc::vec::Vec<OrderLevel>,
    #[prost(message, repeated, tag = "4")]
    pub asks: ::prost::alloc::vec::Vec<OrderLevel>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderLevel {
    #[prost(double, tag = "1")]
    pub price: f64,
    #[prost(double, tag = "2")]
    pub quantity: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HmmRequest {
    #[prost(double, repeated, tag = "1")]
    pub observations: ::prost::alloc::vec::Vec<f64>,
    #[prost(int32, tag = "2")]
    pub n_states: i32,
    #[prost(int32, tag = "3")]
    pub max_iterations: i32,
    #[prost(double, tag = "4")]
    pub tolerance: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HmmResponse {
    #[prost(double, repeated, tag = "1")]
    pub state_probabilities: ::prost::alloc::vec::Vec<f64>,
    #[prost(double, repeated, tag = "2")]
    pub transition_matrix: ::prost::alloc::vec::Vec<f64>,
    #[prost(double, repeated, tag = "3")]
    pub emission_means: ::prost::alloc::vec::Vec<f64>,
    #[prost(double, repeated, tag = "4")]
    pub emission_stds: ::prost::alloc::vec::Vec<f64>,
    #[prost(double, tag = "5")]
    pub log_likelihood: f64,
    #[prost(bool, tag = "6")]
    pub converged: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct McmcRequest {
    #[prost(message, repeated, tag = "1")]
    pub parameters: ::prost::alloc::vec::Vec<ParameterSpace>,
    #[prost(int32, tag = "2")]
    pub n_iterations: i32,
    #[prost(int32, tag = "3")]
    pub burn_in: i32,
    #[prost(double, tag = "4")]
    pub step_size: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParameterSpace {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub min: f64,
    #[prost(double, tag = "3")]
    pub max: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct McmcResponse {
    #[prost(message, repeated, tag = "1")]
    pub samples: ::prost::alloc::vec::Vec<ParameterSample>,
    #[prost(map = "string, double", tag = "2")]
    pub best_params: ::std::collections::HashMap<::prost::alloc::string::String, f64>,
    #[prost(double, tag = "3")]
    pub best_score: f64,
    #[prost(int32, tag = "4")]
    pub acceptance_rate: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParameterSample {
    #[prost(map = "string, double", tag = "1")]
    pub values: ::std::collections::HashMap<::prost::alloc::string::String, f64>,
    #[prost(double, tag = "2")]
    pub score: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SparsePortfolioRequest {
    #[prost(message, repeated, tag = "1")]
    pub prices: ::prost::alloc::vec::Vec<PriceVector>,
    /// "lasso", "elastic_net", "adaptive_lasso"
    #[prost(string, tag = "2")]
    pub method: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub lambda: f64,
    #[prost(double, tag = "4")]
    pub alpha: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SparsePortfolioResponse {
    #[prost(double, repeated, tag = "1")]
    pub weights: ::prost::alloc::vec::Vec<f64>,
    #[prost(int32, tag = "2")]
    pub n_assets_selected: i32,
    #[prost(double, tag = "3")]
    pub objective_value: f64,
    #[prost(map = "string, double", tag = "4")]
    pub metrics: ::std::collections::HashMap<::prost::alloc::string::String, f64>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BoxTaoRequest {
    #[prost(message, repeated, tag = "1")]
    pub prices: ::prost::alloc::vec::Vec<PriceVector>,
    #[prost(double, tag = "2")]
    pub lambda: f64,
    #[prost(double, tag = "3")]
    pub mu: f64,
    #[prost(int32, tag = "4")]
    pub max_iterations: i32,
    #[prost(double, tag = "5")]
    pub tolerance: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BoxTaoResponse {
    #[prost(message, optional, tag = "1")]
    pub low_rank: ::core::option::Option<Matrix>,
    #[prost(message, optional, tag = "2")]
    pub sparse: ::core::option::Option<Matrix>,
    #[prost(message, optional, tag = "3")]
    pub noise: ::core::option::Option<Matrix>,
    #[prost(int32, tag = "4")]
    pub iterations: i32,
    #[prost(bool, tag = "5")]
    pub converged: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Matrix {
    #[prost(int32, tag = "1")]
    pub rows: i32,
    #[prost(int32, tag = "2")]
    pub cols: i32,
    /// Flattened row-major
    #[prost(double, repeated, tag = "3")]
    pub data: ::prost::alloc::vec::Vec<f64>,
}
/// Generated server implementations.
pub mod trading_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with TradingServiceServer.
    #[async_trait]
    pub trait TradingService: Send + Sync + 'static {
        /// Strategy operations
        async fn calculate_mean_reversion(
            &self,
            request: tonic::Request<super::MeanReversionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MeanReversionResponse>,
            tonic::Status,
        >;
        async fn optimize_portfolio(
            &self,
            request: tonic::Request<super::PortfolioOptimizationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PortfolioOptimizationResponse>,
            tonic::Status,
        >;
        async fn detect_regime(
            &self,
            request: tonic::Request<super::RegimeDetectionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegimeDetectionResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the StreamMarketData method.
        type StreamMarketDataStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::MarketDataUpdate, tonic::Status>,
            >
            + Send
            + 'static;
        /// Market data operations
        async fn stream_market_data(
            &self,
            request: tonic::Request<super::StreamRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamMarketDataStream>,
            tonic::Status,
        >;
        async fn get_order_book(
            &self,
            request: tonic::Request<super::OrderBookRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OrderBookResponse>,
            tonic::Status,
        >;
        /// Optimization operations
        async fn run_hmm(
            &self,
            request: tonic::Request<super::HmmRequest>,
        ) -> std::result::Result<tonic::Response<super::HmmResponse>, tonic::Status>;
        async fn run_mcmc(
            &self,
            request: tonic::Request<super::McmcRequest>,
        ) -> std::result::Result<tonic::Response<super::McmcResponse>, tonic::Status>;
        /// Portfolio operations
        async fn calculate_sparse_portfolio(
            &self,
            request: tonic::Request<super::SparsePortfolioRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SparsePortfolioResponse>,
            tonic::Status,
        >;
        async fn box_tao_decomposition(
            &self,
            request: tonic::Request<super::BoxTaoRequest>,
        ) -> std::result::Result<tonic::Response<super::BoxTaoResponse>, tonic::Status>;
    }
    /// Trading service for high-performance Rust-Python communication
    #[derive(Debug)]
    pub struct TradingServiceServer<T: TradingService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: TradingService> TradingServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for TradingServiceServer<T>
    where
        T: TradingService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/hft.TradingService/CalculateMeanReversion" => {
                    #[allow(non_camel_case_types)]
                    struct CalculateMeanReversionSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::UnaryService<super::MeanReversionRequest>
                    for CalculateMeanReversionSvc<T> {
                        type Response = super::MeanReversionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MeanReversionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::calculate_mean_reversion(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = CalculateMeanReversionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hft.TradingService/OptimizePortfolio" => {
                    #[allow(non_camel_case_types)]
                    struct OptimizePortfolioSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::UnaryService<super::PortfolioOptimizationRequest>
                    for OptimizePortfolioSvc<T> {
                        type Response = super::PortfolioOptimizationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PortfolioOptimizationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::optimize_portfolio(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = OptimizePortfolioSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hft.TradingService/DetectRegime" => {
                    #[allow(non_camel_case_types)]
                    struct DetectRegimeSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::UnaryService<super::RegimeDetectionRequest>
                    for DetectRegimeSvc<T> {
                        type Response = super::RegimeDetectionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RegimeDetectionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::detect_regime(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = DetectRegimeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hft.TradingService/StreamMarketData" => {
                    #[allow(non_camel_case_types)]
                    struct StreamMarketDataSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::ServerStreamingService<super::StreamRequest>
                    for StreamMarketDataSvc<T> {
                        type Response = super::MarketDataUpdate;
                        type ResponseStream = T::StreamMarketDataStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StreamRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::stream_market_data(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = StreamMarketDataSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hft.TradingService/GetOrderBook" => {
                    #[allow(non_camel_case_types)]
                    struct GetOrderBookSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::UnaryService<super::OrderBookRequest>
                    for GetOrderBookSvc<T> {
                        type Response = super::OrderBookResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OrderBookRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::get_order_book(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetOrderBookSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hft.TradingService/RunHMM" => {
                    #[allow(non_camel_case_types)]
                    struct RunHMMSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::UnaryService<super::HmmRequest> for RunHMMSvc<T> {
                        type Response = super::HmmResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HmmRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::run_hmm(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = RunHMMSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hft.TradingService/RunMCMC" => {
                    #[allow(non_camel_case_types)]
                    struct RunMCMCSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::UnaryService<super::McmcRequest> for RunMCMCSvc<T> {
                        type Response = super::McmcResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::McmcRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::run_mcmc(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = RunMCMCSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hft.TradingService/CalculateSparsePortfolio" => {
                    #[allow(non_camel_case_types)]
                    struct CalculateSparsePortfolioSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::UnaryService<super::SparsePortfolioRequest>
                    for CalculateSparsePortfolioSvc<T> {
                        type Response = super::SparsePortfolioResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SparsePortfolioRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::calculate_sparse_portfolio(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = CalculateSparsePortfolioSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/hft.TradingService/BoxTaoDecomposition" => {
                    #[allow(non_camel_case_types)]
                    struct BoxTaoDecompositionSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::UnaryService<super::BoxTaoRequest>
                    for BoxTaoDecompositionSvc<T> {
                        type Response = super::BoxTaoResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BoxTaoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::box_tao_decomposition(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = BoxTaoDecompositionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: TradingService> Clone for TradingServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: TradingService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: TradingService> tonic::server::NamedService for TradingServiceServer<T> {
        const NAME: &'static str = "hft.TradingService";
    }
}
