# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import drift_pb2 as drift__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in drift_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DriftServiceStub(object):
    """Portfolio Drift Uncertainty Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PortfolioChoice = channel.unary_unary(
                '/drift.DriftService/PortfolioChoice',
                request_serializer=drift__pb2.ChoiceRequest.SerializeToString,
                response_deserializer=drift__pb2.PortfolioResult.FromString,
                _registered_method=True)
        self.OptimalLiquidation = channel.unary_unary(
                '/drift.DriftService/OptimalLiquidation',
                request_serializer=drift__pb2.LiquidationRequest.SerializeToString,
                response_deserializer=drift__pb2.LiquidationResult.FromString,
                _registered_method=True)
        self.Transition = channel.unary_unary(
                '/drift.DriftService/Transition',
                request_serializer=drift__pb2.TransitionRequest.SerializeToString,
                response_deserializer=drift__pb2.TransitionResult.FromString,
                _registered_method=True)
        self.CalculateVaR = channel.unary_unary(
                '/drift.DriftService/CalculateVaR',
                request_serializer=drift__pb2.RiskRequest.SerializeToString,
                response_deserializer=drift__pb2.RiskMetric.FromString,
                _registered_method=True)
        self.CalculateCVaR = channel.unary_unary(
                '/drift.DriftService/CalculateCVaR',
                request_serializer=drift__pb2.RiskRequest.SerializeToString,
                response_deserializer=drift__pb2.RiskMetric.FromString,
                _registered_method=True)


class DriftServiceServicer(object):
    """Portfolio Drift Uncertainty Service
    """

    def PortfolioChoice(self, request, context):
        """Robust portfolio choice under uncertainty
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OptimalLiquidation(self, request, context):
        """Optimal liquidation under drift uncertainty
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transition(self, request, context):
        """Portfolio transition under drift uncertainty
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateVaR(self, request, context):
        """Calculate Value at Risk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateCVaR(self, request, context):
        """Calculate Expected Shortfall (CVaR)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PortfolioChoice': grpc.unary_unary_rpc_method_handler(
                    servicer.PortfolioChoice,
                    request_deserializer=drift__pb2.ChoiceRequest.FromString,
                    response_serializer=drift__pb2.PortfolioResult.SerializeToString,
            ),
            'OptimalLiquidation': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimalLiquidation,
                    request_deserializer=drift__pb2.LiquidationRequest.FromString,
                    response_serializer=drift__pb2.LiquidationResult.SerializeToString,
            ),
            'Transition': grpc.unary_unary_rpc_method_handler(
                    servicer.Transition,
                    request_deserializer=drift__pb2.TransitionRequest.FromString,
                    response_serializer=drift__pb2.TransitionResult.SerializeToString,
            ),
            'CalculateVaR': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateVaR,
                    request_deserializer=drift__pb2.RiskRequest.FromString,
                    response_serializer=drift__pb2.RiskMetric.SerializeToString,
            ),
            'CalculateCVaR': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateCVaR,
                    request_deserializer=drift__pb2.RiskRequest.FromString,
                    response_serializer=drift__pb2.RiskMetric.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drift.DriftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drift.DriftService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DriftService(object):
    """Portfolio Drift Uncertainty Service
    """

    @staticmethod
    def PortfolioChoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drift.DriftService/PortfolioChoice',
            drift__pb2.ChoiceRequest.SerializeToString,
            drift__pb2.PortfolioResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OptimalLiquidation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drift.DriftService/OptimalLiquidation',
            drift__pb2.LiquidationRequest.SerializeToString,
            drift__pb2.LiquidationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drift.DriftService/Transition',
            drift__pb2.TransitionRequest.SerializeToString,
            drift__pb2.TransitionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateVaR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drift.DriftService/CalculateVaR',
            drift__pb2.RiskRequest.SerializeToString,
            drift__pb2.RiskMetric.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateCVaR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drift.DriftService/CalculateCVaR',
            drift__pb2.RiskRequest.SerializeToString,
            drift__pb2.RiskMetric.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
