# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: options.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\roptions.proto\x12\x07options\"\x99\x01\n\x0cOptionParams\x12\x0c\n\x04spot\x18\x01 \x01(\x01\x12\x0e\n\x06strike\x18\x02 \x01(\x01\x12\x16\n\x0etime_to_expiry\x18\x03 \x01(\x01\x12\x16\n\x0erisk_free_rate\x18\x04 \x01(\x01\x12\x16\n\x0e\x64ividend_yield\x18\x05 \x01(\x01\x12\x12\n\nvolatility\x18\x06 \x01(\x01\x12\x0f\n\x07is_call\x18\x07 \x01(\x08\"_\n\x06Greeks\x12\r\n\x05price\x18\x01 \x01(\x01\x12\r\n\x05\x64\x65lta\x18\x02 \x01(\x01\x12\r\n\x05gamma\x18\x03 \x01(\x01\x12\r\n\x05theta\x18\x04 \x01(\x01\x12\x0c\n\x04vega\x18\x05 \x01(\x01\x12\x0b\n\x03rho\x18\x06 \x01(\x01\"\x9b\x01\n\x0eHedgingRequest\x12%\n\x06option\x18\x01 \x01(\x0b\x32\x15.options.OptionParams\x12\x12\n\nactual_vol\x18\x02 \x01(\x01\x12\x13\n\x0bhedging_vol\x18\x03 \x01(\x01\x12\x17\n\x0fnum_simulations\x18\x04 \x01(\x05\x12\x11\n\tnum_steps\x18\x05 \x01(\x05\x12\r\n\x05\x64rift\x18\x06 \x01(\x01\"Y\n\x0fHedgingResponse\x12\x17\n\x0f\x65xpected_profit\x18\x01 \x01(\x01\x12\x12\n\nprofit_std\x18\x02 \x01(\x01\x12\x19\n\x11guaranteed_profit\x18\x03 \x01(\x01\x32\x91\x01\n\x0eOptionsService\x12\x39\n\x0f\x43\x61lculateGreeks\x12\x15.options.OptionParams\x1a\x0f.options.Greeks\x12\x44\n\x0fSimulateHedging\x12\x17.options.HedgingRequest\x1a\x18.options.HedgingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPTIONPARAMS']._serialized_start=27
  _globals['_OPTIONPARAMS']._serialized_end=180
  _globals['_GREEKS']._serialized_start=182
  _globals['_GREEKS']._serialized_end=277
  _globals['_HEDGINGREQUEST']._serialized_start=280
  _globals['_HEDGINGREQUEST']._serialized_end=435
  _globals['_HEDGINGRESPONSE']._serialized_start=437
  _globals['_HEDGINGRESPONSE']._serialized_end=526
  _globals['_OPTIONSSERVICE']._serialized_start=529
  _globals['_OPTIONSSERVICE']._serialized_end=674
# @@protoc_insertion_point(module_scope)
