# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import options_pb2 as options__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in options_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OptionsServiceStub(object):
    """Options Pricing and Hedging Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateGreeks = channel.unary_unary(
                '/options.OptionsService/CalculateGreeks',
                request_serializer=options__pb2.OptionParams.SerializeToString,
                response_deserializer=options__pb2.Greeks.FromString,
                _registered_method=True)
        self.SimulateHedging = channel.unary_unary(
                '/options.OptionsService/SimulateHedging',
                request_serializer=options__pb2.HedgingRequest.SerializeToString,
                response_deserializer=options__pb2.HedgingResponse.FromString,
                _registered_method=True)


class OptionsServiceServicer(object):
    """Options Pricing and Hedging Service
    """

    def CalculateGreeks(self, request, context):
        """Calculate Option Price and Greeks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulateHedging(self, request, context):
        """Simulate Delta Hedging PnL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OptionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateGreeks': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateGreeks,
                    request_deserializer=options__pb2.OptionParams.FromString,
                    response_serializer=options__pb2.Greeks.SerializeToString,
            ),
            'SimulateHedging': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateHedging,
                    request_deserializer=options__pb2.HedgingRequest.FromString,
                    response_serializer=options__pb2.HedgingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'options.OptionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('options.OptionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OptionsService(object):
    """Options Pricing and Hedging Service
    """

    @staticmethod
    def CalculateGreeks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/options.OptionsService/CalculateGreeks',
            options__pb2.OptionParams.SerializeToString,
            options__pb2.Greeks.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimulateHedging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/options.OptionsService/SimulateHedging',
            options__pb2.HedgingRequest.SerializeToString,
            options__pb2.HedgingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
