# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import regime_pb2 as regime__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in regime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegimeServiceStub(object):
    """Regime-Switching Portfolio Optimization Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Calibrate = channel.unary_unary(
                '/regime.RegimeService/Calibrate',
                request_serializer=regime__pb2.CalibrationRequest.SerializeToString,
                response_deserializer=regime__pb2.PortfolioConfig.FromString,
                _registered_method=True)
        self.Optimize = channel.unary_unary(
                '/regime.RegimeService/Optimize',
                request_serializer=regime__pb2.PortfolioConfig.SerializeToString,
                response_deserializer=regime__pb2.PortfolioResult.FromString,
                _registered_method=True)
        self.SimulatePath = channel.unary_unary(
                '/regime.RegimeService/SimulatePath',
                request_serializer=regime__pb2.SimulationRequest.SerializeToString,
                response_deserializer=regime__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.EstimateRegime = channel.unary_unary(
                '/regime.RegimeService/EstimateRegime',
                request_serializer=regime__pb2.RegimeEstimateRequest.SerializeToString,
                response_deserializer=regime__pb2.RegimeEstimateResponse.FromString,
                _registered_method=True)


class RegimeServiceServicer(object):
    """Regime-Switching Portfolio Optimization Service
    """

    def Calibrate(self, request, context):
        """Calibrate model parameters from historical data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Optimize(self, request, context):
        """Optimize portfolio weights
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulatePath(self, request, context):
        """Simulate wealth path using optimal components
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateRegime(self, request, context):
        """Estimate current market regime
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Calibrate': grpc.unary_unary_rpc_method_handler(
                    servicer.Calibrate,
                    request_deserializer=regime__pb2.CalibrationRequest.FromString,
                    response_serializer=regime__pb2.PortfolioConfig.SerializeToString,
            ),
            'Optimize': grpc.unary_unary_rpc_method_handler(
                    servicer.Optimize,
                    request_deserializer=regime__pb2.PortfolioConfig.FromString,
                    response_serializer=regime__pb2.PortfolioResult.SerializeToString,
            ),
            'SimulatePath': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulatePath,
                    request_deserializer=regime__pb2.SimulationRequest.FromString,
                    response_serializer=regime__pb2.SimulationResponse.SerializeToString,
            ),
            'EstimateRegime': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateRegime,
                    request_deserializer=regime__pb2.RegimeEstimateRequest.FromString,
                    response_serializer=regime__pb2.RegimeEstimateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'regime.RegimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('regime.RegimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegimeService(object):
    """Regime-Switching Portfolio Optimization Service
    """

    @staticmethod
    def Calibrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/regime.RegimeService/Calibrate',
            regime__pb2.CalibrationRequest.SerializeToString,
            regime__pb2.PortfolioConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Optimize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/regime.RegimeService/Optimize',
            regime__pb2.PortfolioConfig.SerializeToString,
            regime__pb2.PortfolioResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimulatePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/regime.RegimeService/SimulatePath',
            regime__pb2.SimulationRequest.SerializeToString,
            regime__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateRegime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/regime.RegimeService/EstimateRegime',
            regime__pb2.RegimeEstimateRequest.SerializeToString,
            regime__pb2.RegimeEstimateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
