# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import superspace_pb2 as superspace__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in superspace_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SuperspaceServiceStub(object):
    """Superspace Anomaly Detection Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectAnomalies = channel.unary_unary(
                '/superspace.SuperspaceService/DetectAnomalies',
                request_serializer=superspace__pb2.DetectRequest.SerializeToString,
                response_deserializer=superspace__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.CalculateChernSimons = channel.unary_unary(
                '/superspace.SuperspaceService/CalculateChernSimons',
                request_serializer=superspace__pb2.CSRequest.SerializeToString,
                response_deserializer=superspace__pb2.CSResponse.FromString,
                _registered_method=True)
        self.GenerateGhostField = channel.unary_unary(
                '/superspace.SuperspaceService/GenerateGhostField',
                request_serializer=superspace__pb2.GhostFieldRequest.SerializeToString,
                response_deserializer=superspace__pb2.GhostFieldResponse.FromString,
                _registered_method=True)


class SuperspaceServiceServicer(object):
    """Superspace Anomaly Detection Service
    """

    def DetectAnomalies(self, request, context):
        """Detect anomalies in time series data using ghost field theory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateChernSimons(self, request, context):
        """Calculate Chern-Simons invariant for a field
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateGhostField(self, request, context):
        """Generate ghost field representation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuperspaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectAnomalies': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectAnomalies,
                    request_deserializer=superspace__pb2.DetectRequest.FromString,
                    response_serializer=superspace__pb2.DetectResponse.SerializeToString,
            ),
            'CalculateChernSimons': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateChernSimons,
                    request_deserializer=superspace__pb2.CSRequest.FromString,
                    response_serializer=superspace__pb2.CSResponse.SerializeToString,
            ),
            'GenerateGhostField': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateGhostField,
                    request_deserializer=superspace__pb2.GhostFieldRequest.FromString,
                    response_serializer=superspace__pb2.GhostFieldResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'superspace.SuperspaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('superspace.SuperspaceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SuperspaceService(object):
    """Superspace Anomaly Detection Service
    """

    @staticmethod
    def DetectAnomalies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/superspace.SuperspaceService/DetectAnomalies',
            superspace__pb2.DetectRequest.SerializeToString,
            superspace__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateChernSimons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/superspace.SuperspaceService/CalculateChernSimons',
            superspace__pb2.CSRequest.SerializeToString,
            superspace__pb2.CSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateGhostField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/superspace.SuperspaceService/GenerateGhostField',
            superspace__pb2.GhostFieldRequest.SerializeToString,
            superspace__pb2.GhostFieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
