# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import meanrev_pb2 as meanrev__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in meanrev_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeanRevServiceStub(object):
    """High-performance, streaming-oriented gRPC service for mean-reversion portfolio analysis
    Designed for: real-time price streams, incremental portfolio optimization, signal generation

    ============ PRICE & DATA STREAMS ============
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EstimateOUParams = channel.stream_stream(
                '/meanrev.MeanRevService/EstimateOUParams',
                request_serializer=meanrev__pb2.PriceUpdate.SerializeToString,
                response_deserializer=meanrev__pb2.OUEstimate.FromString,
                _registered_method=True)
        self.OptimalThresholds = channel.unary_unary(
                '/meanrev.MeanRevService/OptimalThresholds',
                request_serializer=meanrev__pb2.ThresholdRequest.SerializeToString,
                response_deserializer=meanrev__pb2.ThresholdResponse.FromString,
                _registered_method=True)
        self.BacktestWithCosts = channel.stream_stream(
                '/meanrev.MeanRevService/BacktestWithCosts',
                request_serializer=meanrev__pb2.BacktestInput.SerializeToString,
                response_deserializer=meanrev__pb2.BacktestMetric.FromString,
                _registered_method=True)
        self.ComputeLogReturns = channel.unary_unary(
                '/meanrev.MeanRevService/ComputeLogReturns',
                request_serializer=meanrev__pb2.ReturnsRequest.SerializeToString,
                response_deserializer=meanrev__pb2.ReturnsResponse.FromString,
                _registered_method=True)
        self.PCAPortfolios = channel.unary_unary(
                '/meanrev.MeanRevService/PCAPortfolios',
                request_serializer=meanrev__pb2.PCARequest.SerializeToString,
                response_deserializer=meanrev__pb2.PCAResponse.FromString,
                _registered_method=True)
        self.CARAOptimalWeights = channel.stream_stream(
                '/meanrev.MeanRevService/CARAOptimalWeights',
                request_serializer=meanrev__pb2.OptimizationInput.SerializeToString,
                response_deserializer=meanrev__pb2.WeightsOutput.FromString,
                _registered_method=True)
        self.SharpeOptimalWeights = channel.stream_stream(
                '/meanrev.MeanRevService/SharpeOptimalWeights',
                request_serializer=meanrev__pb2.OptimizationInput.SerializeToString,
                response_deserializer=meanrev__pb2.WeightsOutput.FromString,
                _registered_method=True)
        self.MultiperiodOptimize = channel.unary_unary(
                '/meanrev.MeanRevService/MultiperiodOptimize',
                request_serializer=meanrev__pb2.MultiperiodRequest.SerializeToString,
                response_deserializer=meanrev__pb2.MultiperiodResponse.FromString,
                _registered_method=True)
        self.PortfolioStats = channel.unary_unary(
                '/meanrev.MeanRevService/PortfolioStats',
                request_serializer=meanrev__pb2.PortfolioStatsRequest.SerializeToString,
                response_deserializer=meanrev__pb2.PortfolioStatsResponse.FromString,
                _registered_method=True)
        self.GenerateSignals = channel.unary_unary(
                '/meanrev.MeanRevService/GenerateSignals',
                request_serializer=meanrev__pb2.SignalRequest.SerializeToString,
                response_deserializer=meanrev__pb2.SignalResponse.FromString,
                _registered_method=True)
        self.PortfolioHealthStream = channel.unary_stream(
                '/meanrev.MeanRevService/PortfolioHealthStream',
                request_serializer=meanrev__pb2.HealthRequest.SerializeToString,
                response_deserializer=meanrev__pb2.HealthMetric.FromString,
                _registered_method=True)


class MeanRevServiceServicer(object):
    """High-performance, streaming-oriented gRPC service for mean-reversion portfolio analysis
    Designed for: real-time price streams, incremental portfolio optimization, signal generation

    ============ PRICE & DATA STREAMS ============
    """

    def EstimateOUParams(self, request_iterator, context):
        """Bi-directional: Receive price stream, emit OU parameter updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OptimalThresholds(self, request, context):
        """Uni-directional: Send price history, receive optimized portfolio immediately
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BacktestWithCosts(self, request_iterator, context):
        """Bi-directional: Stream prices, receive continuous backtest metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeLogReturns(self, request, context):
        """============ PORTFOLIO OPTIMIZATION ============

        Unary: Batch computation for historical analysis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PCAPortfolios(self, request, context):
        """Unary: PCA portfolio decomposition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CARAOptimalWeights(self, request_iterator, context):
        """Bi-directional: Stream returns over time, get optimal weights continuously
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SharpeOptimalWeights(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultiperiodOptimize(self, request, context):
        """============ ADVANCED ANALYSIS ============

        Unary: Multi-period portfolio optimization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PortfolioStats(self, request, context):
        """Unary: Get portfolio correlations and statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSignals(self, request, context):
        """Unary: Signal generation from thresholds and current price
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PortfolioHealthStream(self, request, context):
        """Uni-directional server streaming: Emit periodic portfolio health checks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeanRevServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EstimateOUParams': grpc.stream_stream_rpc_method_handler(
                    servicer.EstimateOUParams,
                    request_deserializer=meanrev__pb2.PriceUpdate.FromString,
                    response_serializer=meanrev__pb2.OUEstimate.SerializeToString,
            ),
            'OptimalThresholds': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimalThresholds,
                    request_deserializer=meanrev__pb2.ThresholdRequest.FromString,
                    response_serializer=meanrev__pb2.ThresholdResponse.SerializeToString,
            ),
            'BacktestWithCosts': grpc.stream_stream_rpc_method_handler(
                    servicer.BacktestWithCosts,
                    request_deserializer=meanrev__pb2.BacktestInput.FromString,
                    response_serializer=meanrev__pb2.BacktestMetric.SerializeToString,
            ),
            'ComputeLogReturns': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeLogReturns,
                    request_deserializer=meanrev__pb2.ReturnsRequest.FromString,
                    response_serializer=meanrev__pb2.ReturnsResponse.SerializeToString,
            ),
            'PCAPortfolios': grpc.unary_unary_rpc_method_handler(
                    servicer.PCAPortfolios,
                    request_deserializer=meanrev__pb2.PCARequest.FromString,
                    response_serializer=meanrev__pb2.PCAResponse.SerializeToString,
            ),
            'CARAOptimalWeights': grpc.stream_stream_rpc_method_handler(
                    servicer.CARAOptimalWeights,
                    request_deserializer=meanrev__pb2.OptimizationInput.FromString,
                    response_serializer=meanrev__pb2.WeightsOutput.SerializeToString,
            ),
            'SharpeOptimalWeights': grpc.stream_stream_rpc_method_handler(
                    servicer.SharpeOptimalWeights,
                    request_deserializer=meanrev__pb2.OptimizationInput.FromString,
                    response_serializer=meanrev__pb2.WeightsOutput.SerializeToString,
            ),
            'MultiperiodOptimize': grpc.unary_unary_rpc_method_handler(
                    servicer.MultiperiodOptimize,
                    request_deserializer=meanrev__pb2.MultiperiodRequest.FromString,
                    response_serializer=meanrev__pb2.MultiperiodResponse.SerializeToString,
            ),
            'PortfolioStats': grpc.unary_unary_rpc_method_handler(
                    servicer.PortfolioStats,
                    request_deserializer=meanrev__pb2.PortfolioStatsRequest.FromString,
                    response_serializer=meanrev__pb2.PortfolioStatsResponse.SerializeToString,
            ),
            'GenerateSignals': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSignals,
                    request_deserializer=meanrev__pb2.SignalRequest.FromString,
                    response_serializer=meanrev__pb2.SignalResponse.SerializeToString,
            ),
            'PortfolioHealthStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PortfolioHealthStream,
                    request_deserializer=meanrev__pb2.HealthRequest.FromString,
                    response_serializer=meanrev__pb2.HealthMetric.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meanrev.MeanRevService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meanrev.MeanRevService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeanRevService(object):
    """High-performance, streaming-oriented gRPC service for mean-reversion portfolio analysis
    Designed for: real-time price streams, incremental portfolio optimization, signal generation

    ============ PRICE & DATA STREAMS ============
    """

    @staticmethod
    def EstimateOUParams(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/meanrev.MeanRevService/EstimateOUParams',
            meanrev__pb2.PriceUpdate.SerializeToString,
            meanrev__pb2.OUEstimate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OptimalThresholds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meanrev.MeanRevService/OptimalThresholds',
            meanrev__pb2.ThresholdRequest.SerializeToString,
            meanrev__pb2.ThresholdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BacktestWithCosts(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/meanrev.MeanRevService/BacktestWithCosts',
            meanrev__pb2.BacktestInput.SerializeToString,
            meanrev__pb2.BacktestMetric.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeLogReturns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meanrev.MeanRevService/ComputeLogReturns',
            meanrev__pb2.ReturnsRequest.SerializeToString,
            meanrev__pb2.ReturnsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PCAPortfolios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meanrev.MeanRevService/PCAPortfolios',
            meanrev__pb2.PCARequest.SerializeToString,
            meanrev__pb2.PCAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CARAOptimalWeights(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/meanrev.MeanRevService/CARAOptimalWeights',
            meanrev__pb2.OptimizationInput.SerializeToString,
            meanrev__pb2.WeightsOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SharpeOptimalWeights(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/meanrev.MeanRevService/SharpeOptimalWeights',
            meanrev__pb2.OptimizationInput.SerializeToString,
            meanrev__pb2.WeightsOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MultiperiodOptimize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meanrev.MeanRevService/MultiperiodOptimize',
            meanrev__pb2.MultiperiodRequest.SerializeToString,
            meanrev__pb2.MultiperiodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PortfolioStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meanrev.MeanRevService/PortfolioStats',
            meanrev__pb2.PortfolioStatsRequest.SerializeToString,
            meanrev__pb2.PortfolioStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meanrev.MeanRevService/GenerateSignals',
            meanrev__pb2.SignalRequest.SerializeToString,
            meanrev__pb2.SignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PortfolioHealthStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/meanrev.MeanRevService/PortfolioHealthStream',
            meanrev__pb2.HealthRequest.SerializeToString,
            meanrev__pb2.HealthMetric.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
