# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import pair_discovery_pb2 as pair_discovery__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pair_discovery_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PairDiscoveryServiceStub(object):
    """Pair Discovery Service for high-performance cointegration analysis
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TestPair = channel.unary_unary(
                '/pair_discovery.PairDiscoveryService/TestPair',
                request_serializer=pair__discovery__pb2.PairTestRequest.SerializeToString,
                response_deserializer=pair__discovery__pb2.PairTestResponse.FromString,
                _registered_method=True)
        self.DiscoverPairs = channel.unary_stream(
                '/pair_discovery.PairDiscoveryService/DiscoverPairs',
                request_serializer=pair__discovery__pb2.BatchDiscoveryRequest.SerializeToString,
                response_deserializer=pair__discovery__pb2.PairDiscoveryUpdate.FromString,
                _registered_method=True)
        self.SolveHJB = channel.unary_unary(
                '/pair_discovery.PairDiscoveryService/SolveHJB',
                request_serializer=pair__discovery__pb2.HJBRequest.SerializeToString,
                response_deserializer=pair__discovery__pb2.HJBResponse.FromString,
                _registered_method=True)
        self.EstimateOU = channel.unary_unary(
                '/pair_discovery.PairDiscoveryService/EstimateOU',
                request_serializer=pair__discovery__pb2.OUEstimationRequest.SerializeToString,
                response_deserializer=pair__discovery__pb2.OUEstimationResponse.FromString,
                _registered_method=True)
        self.TestCointegration = channel.unary_unary(
                '/pair_discovery.PairDiscoveryService/TestCointegration',
                request_serializer=pair__discovery__pb2.CointegrationRequest.SerializeToString,
                response_deserializer=pair__discovery__pb2.CointegrationResponse.FromString,
                _registered_method=True)
        self.CalculateHurst = channel.unary_unary(
                '/pair_discovery.PairDiscoveryService/CalculateHurst',
                request_serializer=pair__discovery__pb2.HurstRequest.SerializeToString,
                response_deserializer=pair__discovery__pb2.HurstResponse.FromString,
                _registered_method=True)
        self.BacktestStrategy = channel.unary_unary(
                '/pair_discovery.PairDiscoveryService/BacktestStrategy',
                request_serializer=pair__discovery__pb2.BacktestRequest.SerializeToString,
                response_deserializer=pair__discovery__pb2.BacktestResponse.FromString,
                _registered_method=True)


class PairDiscoveryServiceServicer(object):
    """Pair Discovery Service for high-performance cointegration analysis
    """

    def TestPair(self, request, context):
        """Test a single pair for cointegration and mean-reversion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverPairs(self, request, context):
        """Batch discovery with parallel processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SolveHJB(self, request, context):
        """Solve HJB equation for optimal boundaries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateOU(self, request, context):
        """Estimate OU parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestCointegration(self, request, context):
        """Test cointegration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateHurst(self, request, context):
        """Calculate Hurst exponent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BacktestStrategy(self, request, context):
        """Backtest strategy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PairDiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TestPair': grpc.unary_unary_rpc_method_handler(
                    servicer.TestPair,
                    request_deserializer=pair__discovery__pb2.PairTestRequest.FromString,
                    response_serializer=pair__discovery__pb2.PairTestResponse.SerializeToString,
            ),
            'DiscoverPairs': grpc.unary_stream_rpc_method_handler(
                    servicer.DiscoverPairs,
                    request_deserializer=pair__discovery__pb2.BatchDiscoveryRequest.FromString,
                    response_serializer=pair__discovery__pb2.PairDiscoveryUpdate.SerializeToString,
            ),
            'SolveHJB': grpc.unary_unary_rpc_method_handler(
                    servicer.SolveHJB,
                    request_deserializer=pair__discovery__pb2.HJBRequest.FromString,
                    response_serializer=pair__discovery__pb2.HJBResponse.SerializeToString,
            ),
            'EstimateOU': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateOU,
                    request_deserializer=pair__discovery__pb2.OUEstimationRequest.FromString,
                    response_serializer=pair__discovery__pb2.OUEstimationResponse.SerializeToString,
            ),
            'TestCointegration': grpc.unary_unary_rpc_method_handler(
                    servicer.TestCointegration,
                    request_deserializer=pair__discovery__pb2.CointegrationRequest.FromString,
                    response_serializer=pair__discovery__pb2.CointegrationResponse.SerializeToString,
            ),
            'CalculateHurst': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateHurst,
                    request_deserializer=pair__discovery__pb2.HurstRequest.FromString,
                    response_serializer=pair__discovery__pb2.HurstResponse.SerializeToString,
            ),
            'BacktestStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.BacktestStrategy,
                    request_deserializer=pair__discovery__pb2.BacktestRequest.FromString,
                    response_serializer=pair__discovery__pb2.BacktestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pair_discovery.PairDiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pair_discovery.PairDiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PairDiscoveryService(object):
    """Pair Discovery Service for high-performance cointegration analysis
    """

    @staticmethod
    def TestPair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pair_discovery.PairDiscoveryService/TestPair',
            pair__discovery__pb2.PairTestRequest.SerializeToString,
            pair__discovery__pb2.PairTestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverPairs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pair_discovery.PairDiscoveryService/DiscoverPairs',
            pair__discovery__pb2.BatchDiscoveryRequest.SerializeToString,
            pair__discovery__pb2.PairDiscoveryUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SolveHJB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pair_discovery.PairDiscoveryService/SolveHJB',
            pair__discovery__pb2.HJBRequest.SerializeToString,
            pair__discovery__pb2.HJBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateOU(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pair_discovery.PairDiscoveryService/EstimateOU',
            pair__discovery__pb2.OUEstimationRequest.SerializeToString,
            pair__discovery__pb2.OUEstimationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestCointegration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pair_discovery.PairDiscoveryService/TestCointegration',
            pair__discovery__pb2.CointegrationRequest.SerializeToString,
            pair__discovery__pb2.CointegrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateHurst(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pair_discovery.PairDiscoveryService/CalculateHurst',
            pair__discovery__pb2.HurstRequest.SerializeToString,
            pair__discovery__pb2.HurstResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BacktestStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pair_discovery.PairDiscoveryService/BacktestStrategy',
            pair__discovery__pb2.BacktestRequest.SerializeToString,
            pair__discovery__pb2.BacktestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
