# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import trading_pb2 as trading__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trading_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradingServiceStub(object):
    """Trading service for high-performance Rust-Python communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateMeanReversion = channel.unary_unary(
                '/hft.TradingService/CalculateMeanReversion',
                request_serializer=trading__pb2.MeanReversionRequest.SerializeToString,
                response_deserializer=trading__pb2.MeanReversionResponse.FromString,
                _registered_method=True)
        self.OptimizePortfolio = channel.unary_unary(
                '/hft.TradingService/OptimizePortfolio',
                request_serializer=trading__pb2.PortfolioOptimizationRequest.SerializeToString,
                response_deserializer=trading__pb2.PortfolioOptimizationResponse.FromString,
                _registered_method=True)
        self.DetectRegime = channel.unary_unary(
                '/hft.TradingService/DetectRegime',
                request_serializer=trading__pb2.RegimeDetectionRequest.SerializeToString,
                response_deserializer=trading__pb2.RegimeDetectionResponse.FromString,
                _registered_method=True)
        self.StreamMarketData = channel.unary_stream(
                '/hft.TradingService/StreamMarketData',
                request_serializer=trading__pb2.StreamRequest.SerializeToString,
                response_deserializer=trading__pb2.MarketDataUpdate.FromString,
                _registered_method=True)
        self.GetOrderBook = channel.unary_unary(
                '/hft.TradingService/GetOrderBook',
                request_serializer=trading__pb2.OrderBookRequest.SerializeToString,
                response_deserializer=trading__pb2.OrderBookResponse.FromString,
                _registered_method=True)
        self.RunHMM = channel.unary_unary(
                '/hft.TradingService/RunHMM',
                request_serializer=trading__pb2.HMMRequest.SerializeToString,
                response_deserializer=trading__pb2.HMMResponse.FromString,
                _registered_method=True)
        self.RunMCMC = channel.unary_unary(
                '/hft.TradingService/RunMCMC',
                request_serializer=trading__pb2.MCMCRequest.SerializeToString,
                response_deserializer=trading__pb2.MCMCResponse.FromString,
                _registered_method=True)
        self.CalculateSparsePortfolio = channel.unary_unary(
                '/hft.TradingService/CalculateSparsePortfolio',
                request_serializer=trading__pb2.SparsePortfolioRequest.SerializeToString,
                response_deserializer=trading__pb2.SparsePortfolioResponse.FromString,
                _registered_method=True)
        self.BoxTaoDecomposition = channel.unary_unary(
                '/hft.TradingService/BoxTaoDecomposition',
                request_serializer=trading__pb2.BoxTaoRequest.SerializeToString,
                response_deserializer=trading__pb2.BoxTaoResponse.FromString,
                _registered_method=True)


class TradingServiceServicer(object):
    """Trading service for high-performance Rust-Python communication
    """

    def CalculateMeanReversion(self, request, context):
        """Strategy operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OptimizePortfolio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectRegime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMarketData(self, request, context):
        """Market data operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunHMM(self, request, context):
        """Optimization operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunMCMC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateSparsePortfolio(self, request, context):
        """Portfolio operations  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BoxTaoDecomposition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateMeanReversion': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateMeanReversion,
                    request_deserializer=trading__pb2.MeanReversionRequest.FromString,
                    response_serializer=trading__pb2.MeanReversionResponse.SerializeToString,
            ),
            'OptimizePortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizePortfolio,
                    request_deserializer=trading__pb2.PortfolioOptimizationRequest.FromString,
                    response_serializer=trading__pb2.PortfolioOptimizationResponse.SerializeToString,
            ),
            'DetectRegime': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectRegime,
                    request_deserializer=trading__pb2.RegimeDetectionRequest.FromString,
                    response_serializer=trading__pb2.RegimeDetectionResponse.SerializeToString,
            ),
            'StreamMarketData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMarketData,
                    request_deserializer=trading__pb2.StreamRequest.FromString,
                    response_serializer=trading__pb2.MarketDataUpdate.SerializeToString,
            ),
            'GetOrderBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderBook,
                    request_deserializer=trading__pb2.OrderBookRequest.FromString,
                    response_serializer=trading__pb2.OrderBookResponse.SerializeToString,
            ),
            'RunHMM': grpc.unary_unary_rpc_method_handler(
                    servicer.RunHMM,
                    request_deserializer=trading__pb2.HMMRequest.FromString,
                    response_serializer=trading__pb2.HMMResponse.SerializeToString,
            ),
            'RunMCMC': grpc.unary_unary_rpc_method_handler(
                    servicer.RunMCMC,
                    request_deserializer=trading__pb2.MCMCRequest.FromString,
                    response_serializer=trading__pb2.MCMCResponse.SerializeToString,
            ),
            'CalculateSparsePortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateSparsePortfolio,
                    request_deserializer=trading__pb2.SparsePortfolioRequest.FromString,
                    response_serializer=trading__pb2.SparsePortfolioResponse.SerializeToString,
            ),
            'BoxTaoDecomposition': grpc.unary_unary_rpc_method_handler(
                    servicer.BoxTaoDecomposition,
                    request_deserializer=trading__pb2.BoxTaoRequest.FromString,
                    response_serializer=trading__pb2.BoxTaoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hft.TradingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hft.TradingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingService(object):
    """Trading service for high-performance Rust-Python communication
    """

    @staticmethod
    def CalculateMeanReversion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore[attr-defined]
            request,
            target,
            '/hft.TradingService/CalculateMeanReversion',
            trading__pb2.MeanReversionRequest.SerializeToString,
            trading__pb2.MeanReversionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OptimizePortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore[attr-defined]
            request,
            target,
            '/hft.TradingService/OptimizePortfolio',
            trading__pb2.PortfolioOptimizationRequest.SerializeToString,
            trading__pb2.PortfolioOptimizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectRegime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore[attr-defined]
            request,
            target,
            '/hft.TradingService/DetectRegime',
            trading__pb2.RegimeDetectionRequest.SerializeToString,
            trading__pb2.RegimeDetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(  # type: ignore[attr-defined]
            request,
            target,
            '/hft.TradingService/StreamMarketData',
            trading__pb2.StreamRequest.SerializeToString,
            trading__pb2.MarketDataUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore[attr-defined]
            request,
            target,
            '/hft.TradingService/GetOrderBook',
            trading__pb2.OrderBookRequest.SerializeToString,
            trading__pb2.OrderBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunHMM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore[attr-defined]
            request,
            target,
            '/hft.TradingService/RunHMM',
            trading__pb2.HMMRequest.SerializeToString,
            trading__pb2.HMMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunMCMC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore[attr-defined]
            request,
            target,
            '/hft.TradingService/RunMCMC',
            trading__pb2.MCMCRequest.SerializeToString,
            trading__pb2.MCMCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateSparsePortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore[attr-defined]
            request,
            target,
            '/hft.TradingService/CalculateSparsePortfolio',
            trading__pb2.SparsePortfolioRequest.SerializeToString,
            trading__pb2.SparsePortfolioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BoxTaoDecomposition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore[attr-defined]
            request,
            target,
            '/hft.TradingService/BoxTaoDecomposition',
            trading__pb2.BoxTaoRequest.SerializeToString,
            trading__pb2.BoxTaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
